### ISSUE TITLE
PLL_Links_Model::switch_language_in_link() error

### ISSUE THREAD

**Issue by homewardmedia** [polylang/polylang#139]
Getting this on all of my translated pages:

Warning: Missing argument 2 for PLL_Links_Model::switch_language_in_link(), called in *wp-includes/class-wp-hook.php on line 298 and defined in */wp-content/plugins/polylang/include/links-model.php on line 42

**Comment by Chouby** [comment]
This is probably probably due to a wrong interaction with your theme or another plugin. Could deactivate all them one by one (including the theme, but keeping Polylang always activated) and tell me which one it is?

**Comment by ripieces** [comment]
We have the same problem, it happens when this plug-in is active: https://wordpress.org/plugins/custom-permalinks/

**Comment by Chouby** [comment]
@ripieces Unfortunately, Custom Permalinks is known to conflict with Polylang.
@homewardmedia Are you using Custom Permalinks too?

**Comment by enzolutions** [comment]
I have the same issue with Custom Permalinks and Permalinks Customizer

**Comment by samiahmedsiddiqui** [comment]
Hey guys, I have made a quick fix and published in the last version. I thought the issue was resolved. 

Can you guys elaborate the use cases. I don't use the Polylang Plugin so, doesn't know much about it.

**Comment by ripieces** [comment]
Thank you for your reply.

I tried really hard (several hours) now to reproduce the issue on a clean Wordpress install (and not just all other plug-ins than Custom Permalinks and Polylang deactivated).

I am unable to reproduce that exact issue now (the one with the PHP Warning).
The only issues I get now are redirect loops.

So I am guessing it's a more complicated problem that has to do with the way and order things were updated and installed over time.

The problem is, that Polyalang changes the way permalinks work (i.e. Prefixes other language pages with /two-letter-language-code-here/ and I guess that does not work well with Custom Permalinks, because it changes that too.
Thus Polylang and Custom Permalinks are unable to work together at the moment I guess.

Thank you for your time.

**Comment by samiahmedsiddiqui** [comment]
Hey, thanks for doing tests and provide such a valueable feedback. 

Redirect Loop is in my knowledge and i was added 1 fix for it about 1 or 2 months ago. My fix was initially solved the issue for me. But, as i said earlier i am not polylang user. So, i have just made an fix and give a quick test though and publish it.

I didn't do much testing at that time. I'll recheck the issue on my hand and try to create some fix (if i'll able to produce the issue).

Thanks again,
Sami

**Comment by Chouby** [comment]
I reproduced the error. With both Polylang and Custom Permalinks activated, modify a page slug and save.

I traced it back to the filter `wpml_permalink` applied at line 67 in custom-permalinks.php. The issue is coming from the fact that the function attached to this filter needs two parameters in Polylang (the second parameter being a language), while the second parameter is optional in the equivalent function in WPML.

However I believe that this filter is wrongly applied. With Polylang we get the warning but this is as wrong in WPML as the page permalink changes according to the current language.

For example, on admin side, the permalink will be `mysite.com/en/test` when having the admin language filter (in the admin bar) on English. And the permalink will be `mysite.com/all/test` when having the admin language filter displaying "all languages" . This result in a non-constant page permalink, with som of them linking to a 404 page.

**Comment by Chouby** [comment]
I closed this topic by solving the PHP warning. The 2nd parameter is now optional and defaults to the current language as in WPML. There is still however a difference as Polylang will prefer not to add any language code rather than adding /all/ when the admin language switcher displays all languages.

The compatibility issue with Custom permalinks is however not solved due to the fact the applying the `wpml_permalink` filter without second parameter makes the permalink not constant.

**Comment by samiahmedsiddiqui** [comment]
@Chouby How your plugin handles this filter?
 apply_filters( 'wpml_permalink', home_url()."/".$custom_permalink );

What's the second parameter do you need? If i provide the filter for your plugin here so, can that works for you?

**Comment by Chouby** [comment]
The filter `wpml_permalink` is usually used to add a language code in the url. This language code is provided as second argument. See https://wpml.org/wpml-hook/wpml_permalink/

If you don't provide this second argument, the current language will be used. The issue in Polylang compared to WPML prior to https://github.com/polylang/polylang/commit/93a12b67c2a57444d588aa1edbfef70c1df2ad02 was this second parameter not being optional. 

The issue in Custom Permalinks is that the current language is not necessary the language of the page so the obtained permalink is not always the right one. You should pass the language code of the page as second argument. It can be obtained with the filter `wpml_element_language_code`. See https://wpml.org/wpml-hook/wpml_element_language_code/

Something like
```php
function custom_permalinks_page_link( $permalink, $page ) {
	$custom_permalink = get_post_meta( $page, 'custom_permalink', true );
	if ( $custom_permalink ) {
		$language_code = apply_filters( 'wpml_element_language_code', null, array( 'element_id' => $page, 'element_type' => 'page' ) );
		return apply_filters( 'wpml_permalink', home_url( '/' . $custom_permalink ), $language_code );
	}

	return $permalink;
}```
should do what you want. This should work both with Polylang and WPML as both filters exist in the 2 plugins. 

NB1: I fixed the `home_url` usage as described in https://wordpress.org/support/topic/misuse-of-the-function-home_url-and-compatibility-with-polylang/ 
NB2: Take care with `wpml_element_language_code`. For taxonomies, it is expecting the term_taxonomy_id, not the term_id.

**Comment by samiahmedsiddiqui** [comment]
@Chouby I have updated the code. Could please test this with your plugin and provide me your feedback?

If some other person can try this update and provide their feedback so, that would wonderful.

[Uploading custom-permalinks.zip…]()

**Comment by grappler** [comment]
@samiahmedsiddiqui The Zip file did not fully upload.

**Comment by samiahmedsiddiqui** [comment]
Sorry guys, my bad.  Thanks @grappler for informing me :)

Here is the file:
[custom-permalinks.zip](https://github.com/polylang/polylang/files/1133023/custom-permalinks.zip)

**Comment by Chrystll** [comment]
Custom Permalinks 0.9.2
Polylang 2.1.5
WordPress 4.8

My settings:
Settings > Permalinks: Post name
Languages > Settings > Urls modifications module: check only 'The language is set from the directory name in pretty permalinks'

Hi Sami

1. I just tested your last version with Polylang 2.1.5 and I noticed that the language code is in the editable field. And when removing or modifying it I get a 404 error. But it works if you don't edit it (remove or modify). I noticed that with WPML the language code is not in the editable field.

2. I noticed a bug with child pages when you decide to display the page name instead the language code in the front page: for example mysite.com/accueil/ instead of mysite.com

To reproduce:
keep uncheck 'The front page url contains the language code instead of the page name or page id' in Languages > Settings > Urls modifications module.

Create a parent page in the English language for example (slug: /en/parent-page-en), then create its child page (slug: /en/parent-page-en/child-page-en).

Add this child page in your English menu. Go to Front > menu: click on it: you get your child page correctly with the url: mysite.com/en/page-parent-en/child-page-en/

Go back to your wp-admin, edit the child page, then remove 'parent-page-en'.

Go to Front > menu: click on your child page: you get mysite.com/en/home-en/en/child-page-en/ with a 404 error.

The origin of this bug is connected to: https://wordpress.org/support/topic/misuse-of-the-function-home_url-and-compatibility-with-polylang/

**Comment by samiahmedsiddiqui** [comment]
@Chrystll Have you tested it with file i have attached above or you have downloaded the plugins from the wordpress?

**Comment by Chrystll** [comment]
@samiahmedsiddiqui 
I tested with the file you attached above.

**Comment by samiahmedsiddiqui** [comment]
Thanks @Chrystll for providing your feedback. Actually, it's quite hectic week going for me. Would go through you steps and try to create resolve the issue as soon as possible.

Also, i'll ping you if i need some more information.

Thanks Again :)

**Comment by samiahmedsiddiqui** [comment]
Hey @Chrystll 

Attaching One more patch, Please test it again with this version 0.9.3.

[custom-permalinks.zip](https://github.com/polylang/polylang/files/1150979/custom-permalinks.zip)


Thanks,
Sami

**Comment by Chrystll** [comment]
Hi @samiahmedsiddiqui

Thanks a lot for your version 0.9.3. I tested it with Polylang (free version) and it solved the bug I mentioned. That's great.

**Comment by Chouby** [comment]
@samiahmedsiddiqui May I suggest to replace 
`is_plugin_active("polylang/polylang.php")`
by
`defined( 'POLYLANG_VERSION' )`?
This would allow to be compatible with Polylang and Polylang Pro at teh same time.

**Comment by samiahmedsiddiqui** [comment]
Thanks @Chrystll  for your valueable feedback.

@Chouby I'll update that. Anything else you would like to suggest and does we are compatible now?

**Comment by Chouby** [comment]
I just fixed an issue which was on our end. See #149.
@Chrystll will go on testing and inform us here if there is another issue she detects.

**Comment by samiahmedsiddiqui** [comment]
@Chouby Thanks for fixing that issue.

I really want to make my both of the permalink plugins (Custom Permalink and Permalinks Customizer) to be compatible with this plugin. I hope, that we make this happen and users can use our plugins at the same time rather than choosing one of the plugin between these.

Here is the git repo for my both Permalink Plugins:
https://github.com/yasglobal/custom-permalinks
https://github.com/yasglobal/permalinks-customizer

I have used this line:
`defined( 'POLYLANG_VERSION' )`
You can find the Patch to resolve the conflicts, here:
https://github.com/yasglobal/custom-permalinks/tree/develop
https://github.com/yasglobal/permalinks-customizer/tree/develop
